name: tarsier_mysql_storage
description: A simple and flexible library for managing MySQL databases in Dart and Flutter applications.
version: 1.0.3
homepage: https://github.com/marianz-bonfire/tarsier_mysql_storage
repository: https://github.com/marianz-bonfire/tarsier_mysql_storage
issue_tracker: https://github.com/marianz-bonfire/tarsier_mysql_storage/issues

topics:
  - tarsier
  - storage
  - mysql

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  windows:
  linux:
  macos:
environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  mysql_client: ^0.0.27
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.1.1
  test: ^1.24.0

screenshots:
  - description: The package logo.
    path: assets/logo.png